config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'vehicle_histories/search'
  resources :parking_slots, only: [:index, :show] do
    member do
      post 'exit'
    end
  end

  resources :vehicle_histories, only: [] do
    collection do
      get 'search'
    end
  end


  get 'available_parking_slots/:entry_point', to: 'parking_slots#available_parking_slots', as: :available_parking_slots

  resources :vehicles, only: [:new, :create, :show]


  # get 'search_vehicle_histories', to: 'vehicle_histories#search', as: :search_vehicle_histories

  root 'vehicles#new'
  resources :vehicles do
    get 'new/:id', to: 'vehicles#new', on: :member, as: :new_with_id
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parking_slot.rb
class ParkingSlot < ApplicationRecord
  has_one :vehicle
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :parking_slot
  has_one :vehicle_history

  validate :entry_within_24_hours, on: :create


  def entry_within_24_hours
    if Vehicle.where('registration_number = ? AND entry_time >= ?', registration_number, 24.hours.ago).exists?
      errors.add(:base, 'Vehicle already entered within the last 24 hours.')
    end
  end

  def vehicle_params
    params.require(:vehicle).permit(:registration_number, :entry_time)
  end

end

app/models/vehicle_history.rb
class VehicleHistory < ApplicationRecord
  belongs_to :vehicle
  belongs_to :parking_slot
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/parking_slots_controller.rb
class ParkingSlotsController < ApplicationController

  def index
    @entry_point = params[:entry_point]
    @available_slot = ParkingSlot.find_by(entry_point: @entry_point, status: 'available')

    if @available_slot
      @available_slot.update(status: 'booked')
      redirect_to parking_slot_path(@available_slot)
    else
      flash[:alert] = 'No available parking slots at this entry point.'
      redirect_to root_path
    end
  end

  def create
    @entry_point = params[:entry_point]
    @available_slot = ParkingSlot.find_by(entry_point: @entry_point, status: 'available')

    if @available_slot
      @available_slot.update(status: 'booked')

      # Create a new VehicleHistory record when a vehicle enters
      VehicleHistory.create(
        vehicle: @available_slot.vehicle,
        entry_point: @entry_point,
        status: 'entered',
        entered_at: Time.now
      )

      redirect_to parking_slot_path(@available_slot)
    else
      flash[:alert] = 'No available parking slots at this entry point.'
      redirect_to root_path
    end
  end

  def exit
    @parking_slot = ParkingSlot.find(params[:id])

    if @parking_slot.update(status: 'available')
      flash[:notice] = 'Parking slot has been marked as available.'

      vehicle_history = VehicleHistory.find_by(
        vehicle: @parking_slot.vehicle,
        entry_point: @parking_slot.entry_point,
        status: 'entered'
      )

      if vehicle_history
        vehicle_history.update(status: 'exited', exited_at: Time.now)
      end


    else
      flash[:alert] = 'Failed to update parking slot status.'
    end

    redirect_to parking_slots_path(entry_point: @parking_slot.entry_point)

  end

  def show
    @parking_slot = ParkingSlot.params[:id]
  end

  private

  def parking_slot_params
    params.require(:parking_slot).permit(:number, :entry_point, :status)
  end
end

app/controllers/vehicle_histories_controller.rb
class VehicleHistoriesController < ApplicationController
  def search
    registration_number = params[:registration_number]
    @vehicle_histories = VehicleHistory.includes(:vehicle, :parking_slot)
                                       .where(vehicle: { registration_number: registration_number })
                                       .order(entered_at: :desc)

  end
end

app/controllers/vehicles_controller.rb
  class VehiclesController < ApplicationController
    before_action :authenticate_user!


    def new
      @vehicle = Vehicle.new
    end

    def show
      @vehicle = Vehicle.find(params[:id])
    end

    def create
      @vehicle = Vehicle.new(vehicle_params)
      @vehicle.entry_time = Time.now  # Set the entry timestamp

      if @vehicle.save
        entry_point = @vehicle.entry_point

        VehicleHistory.create(
                vehicle: @vehicle,
                entry_point: @vehicle.entry_point,
                parking_slot: @vehicle.parking_slot,
                status: 'entered',
                entered_at: Time.now
              )

        redirect_to parking_slot_path(@vehicle.parking_slot)

        if @available_slot
          # Assign the parking slot to the vehicle
          @vehicle.parking_slot = @available_slot
          @available_slot.update(status: 'booked')
          flash[:notice] = 'Vehicle entered parking successfully.'

        else
          flash[:alert] = 'No available parking slots at this entry point.'
          redirect_to root_path
        end
      else
        flash[:alert] = 'Failed to enter the parking.'
        render :new
      end
    end

    private

    def vehicle_params
      params.require(:vehicle).permit(:entry_point, :registration_number)
    end
  end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parking_slots_helper.rb
module ParkingSlotsHelper
end

app/helpers/vehicle_histories_helper.rb
module VehicleHistoriesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParkingSlotFinal</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application' %>
</head>
<body>
<% if user_signed_in? %>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign In', new_user_session_path %>
<% end %>

<%= yield %>
</body>
</html>

app/views/parking_slots/index.html.erb
<h1>Available Parking Slots</h1>
<% if @available_slots.any? %>
  <ul>
    <% @available_slots.each do |slot| %>
      <li class="parking-slot">
        Slot Number: <%= slot.number %><br>
        Entry Point: <%= slot.entry_point %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No available parking slots at the moment.</p>
<% end %>

app/views/parking_slots/show.html.erb
<h1>Parking Slot Details</h1>
<%= render 'shared/messages' %>

<% if @parking_slot %>
  <p>Slot Number: <%= @parking_slot.number %></p>
  <p>Entry Point: <%= @parking_slot.entry_point %></p>
  <p>Status: <%= @parking_slot.status %></p>

  <!-- Form for entering vehicle registration number -->
  <%= form_with(model: @vehicle, url: vehicles_path, method: :post) do |form| %>
    <div class="field">
      <br>
      <%= form.label :registration_number, 'Enter Vehicle Registration Number' %>
      <%= form.text_field :registration_number %>
    </div>
    <br>
    <%= form.submit 'Register Vehicle' %>
  <% end %>

  <%= link_to 'Exit Parking', parking_slot_exit_path(@parking_slot), method: :post %>
  <%= link_to 'View Parking Slot', parking_slots_path(entry_point: @parking_slot.entry_point) %>
<% else %>
  <p>No parking slot available at this entry point.</p>
<% end %>

app/views/shared/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/vehicle_histories/_search.html.erb
<!-- app/views/vehicle_histories/_search.html.erb -->

<%= form_tag(search_vehicle_histories_path, method: :get) do %>
  <div class="field">
    <%= label_tag :registration_number, 'Enter Vehicle Registration Number:' %>
    <%= text_field_tag :registration_number, params[:registration_number] %>
  </div>
<br>
  <%= submit_tag 'Search' %>
<% end %>
<br>
<%= link_to 'Back', parking_slots_path(@parking_slot), method: :post %>

app/views/vehicle_histories/search.html.erb
<!-- app/views/vehicle_histories/search.html.erb -->

<h1>Vehicle History Search Results</h1>

<%= render 'search' %>

<% if @vehicle_histories.any? %>
  <table>
    <thead>
    <tr>
      <th>Vehicle Registration Number</th>
      <th>Entry Point</th>
      <th>Parking Slot</th>
      <th>Status</th>
      <th>Entered At</th>
      <th>Exited At</th>
    </tr>
    </thead>
    <tbody>
    <% @vehicle_histories.each do |history| %>
      <tr>
        <td><%= history.vehicle.registration_number %></td>
        <td><%= history.entry_point %></td>
        <td><%= history.parking_slot.number %></td>
        <td><%= history.status %></td>
        <td><%= history.entered_at %></td>
        <td><%= history.exited_at %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>No vehicle history found for the provided registration number.</p>
<% end %>

app/views/vehicles/new.html.erb
<%= form_with(model: @vehicle, url: vehicles_path, method: :post, class: 'vehicle-form') do |form| %>
  <div class="display">
    <div class="field">
      <%= form.label :entry_point, 'Entry Point Number:', class: 'form-label' %>
      <%= form.number_field :entry_point, min: 1, max: 4, class: 'form-input' %>
    </div>

    <div class="field">
      <%= form.label :registration_number, 'Vehicle Registration Number:', class: 'form-label' %>
      <%= form.text_field :registration_number, class: 'form-input' %>
    </div>

    <div class="actions">
      <%= form.submit 'Enter Parking', class: 'submit-button' %>
    </div>
<% end %>
<br>
<%= link_to 'Search Vehicle History', vehicle_histories_search_path, class: 'btn btn-primary' %>
</div>